Fixed Webhook Issue - OP-21224
OpsMx/echo-oes pull request #22
Opened 2023-10-09 09:25 UTC by aman-agrawal

## Summary

**Issue :** https://devopsmx.atlassian.net/browse/OP-21224
**Solution :** Fixed the java code

### How changes are verified
Create & deploy docker img with given changes : aman1603/trigger:fixed2 & found that pipeline is triggering successfully on github commit

## Documentation Updates
Do we need to update dashboards? No
Do we need to update SOP, new hire wiki or other documents? No

## Rollback, Deployment Details
Can this change be rolled back automatically without any issue?  Yes
Is this a backwards-compatible change in your opinion ?  Yes
**Pre deployment steps :** NA
**Post deployment steps :** NA

2023-10-09 10:55 UTC, jsoundar22 requested changes

2023-10-09 10:55 UTC, jsoundar22 commented on echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BaseTriggerEventHandler.java
> +      return supportedTriggerTypes().stream()
we should make it as if-elseif-else block, instead of multiple return stmt from a clean coding PoV

2023-10-09 10:55 UTC, jsoundar22 commented on echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandler.java
> +        lastBuild != null
What is the need to remove the parenthesis? its always a best practise to enclose in paranthesis, when you have multiple logical conditions

2023-10-09 10:55 UTC, jsoundar22 commented on echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BuildEventHandler.java
> +        lastBuild != null
same as above

2023-10-09 11:15 UTC, sudhakaropsmx requested changes

2023-10-09 11:15 UTC, sudhakaropsmx commented on echo-pipelinetriggers/src/main/java/com/netflix/spinnaker/echo/pipelinetriggers/eventhandlers/BaseTriggerEventHandler.java
> -    log.debug("Start of the get matching Pipelines - BaseTriggerEventHandler");
Please keep log statements

2023-10-10 07:52 UTC, jsoundar22 approved these changes
Looks good

2023-10-10 08:03 UTC, merged